#! /bin/bash

#############################################################
# BDH - Easy and safe way to monitor Unix and Linux FS use  #
# AUTHOR - Leonardo Macedo | macedojleo@gmail.com           #
# FIRST RELEASE: 2013                                       #
# LAST UPDATED: 02-19-2019                                  #
#	        - Now you can customize thresholds.         #
#               - Send alerts to slack through webhook app. #
#               - Deamon mode.                              #
#               - Log files                                 #
#	        - STOP -s or -S                             #
#		- Fix bugs.                                 #
#############################################################

#set alarm thresholds here:                                   

Def_major="70";
Def_critical="85";
Def_urgent="95";

#File that stores the PID program
prFile=".bdhpid";

#Put your incoming Slack app webhook URL here:

SlackWebHook="https://hooks.slack.com/services/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"

usage()
{
  echo -e "Usage: $0 [-t | -g | -m | -k ] [ -d Interval in seconds ] [-s]"
  echo -e "\t OPTIONS:"
  echo -e "\t -g or -G show all FS as Gb values."
  echo -e "\t -m or -M show all FS as Mb values."
  echo -e "\t -k or -K show all FS as Kb values."
  echo -e "\t -d or -D [INTERVAL IN SECONDS] - Daemon mode. It will send alert messages to SLACK using WEBHOOK APP"
  echo -e "\t -s or -S - Stop bdh daemon process"
  exit 2
}

log ()
{
 #Change here logdir (log will be generated only in daemon mode).
 logdir="/tmp";

 fs=$1;
 used=$2;
 free=$3;
 percent=$4;
 logType=$5;
 PRG_PID=$6;
 other=$7;
 timeStamp=`date +%D-%H:%M:%S`;
 logTimeStamp=`date +%m%d%y`;

 if [ ! -d $logdir ];then
	 echo "$logdir does not exists! Impossible to write file $logdir/bdh_$logTimeStamp.log";
	 exit 1;
 fi

 if [[ $logType != "START"  &&  $logType != "STOP" ]]; then
	 echo $logType " | " $timeStamp" | FS:" $fs "| Used:" $used "kb | Free:" $free "kb | "$percent"%" >> $logdir/bdh_$logTimeStamp.log
 elif [[ $logType == "START" ]]; then
	echo "$logType  |  $timeStamp | PID:  $PRG_PID INTERVAL: $other | logFile: $logdir/bdh_$logTimeStamp.log" >> $logdir/bdh_$logTimeStamp.log;
 elif [[ $logType == "STOP" ]];then
	echo "$logType  |  $timeStamp | Process stopped by $other" >> $logdir/bdh_$logTimeStamp.log;
 fi

}

alert()
{

 url=$1;
 messageType=$2;
 FS=$3;
 used=$4;
 free=$5;
 icon=$6;
 timeStamp=`date +%D-%H:%M:%S`;
 msg="$messageType: $icon FS $FS has only $free Kb free ( $used% used ) - $timeStamp";
 json="{\"text\":\"$msg\"}";
 #curl -X POST -H 'Content-type: application/json' --data '{"text":\"$msg\"}' $url
 curl -s -d "payload=$json" "$url" 1>/dev/null;

}

while getopts d:D:gGmMkKhHsS OPTION; do
 
 case $OPTION in
 g | G )

        Filesystem=`df -Pk | grep -v ^Filesystem | sed "s#%##g"`;

        for FS in "$Filesystem"; do
		echo "$FS" | awk -v THR_urg="$Def_urgent" -v  THR_cri="$Def_critical" -v THR_maj="$Def_major"  'BEGIN {
                                        format_header="%-50s %-10s %-12s %-15s %-8s %-8s\n"
                                        use_format="";
					metricType="Gb";
                                        printf(format_header, "MOUNT POINT", "TOTAL", "USED", "AVAILABLE", "IN USE", "FS");
                                }

                                {

					total=$2/1024/1024;
                                        used=$3/1024/1024;
                                        available=$4/1024;
                                        F_total=sprintf("%.0f", total);
                                        F_used=sprintf("%.0f", used);
                                        F_available=sprintf("%.0f", available);

                                        format="%-50s %-10s %-12s %-15s %-8s %-8s\n";
                                        urgent="\033[5;31;1m" format "\033[0m";
                                        critical="\033[31;1m" format "\033[0m";
                                        major="\033[33;1m" format "\033[0m";
                                        normal="\033[37;1m" format "\033[0m";
                                        low="\033[32;1m" format "\033[0m";

                                        if ($5 >= THR_maj && $5 < THR_cri) { use_format=major; }
                                        else if ( $5 >= THR_cri && $5 <= THR_urg) { use_format=critical;}
                                        else if ( $5 >= THR_urg ) {use_format=urgent;}
                                        else {use_format=normal;}
					printf(use_format, $1, F_total"("metricType")", F_used "("metricType")", F_available"("metricType")", $5"%", $6)


                                }'
        done
 ;;

 m | M )

        Filesystem=`df -Pk | grep -v ^Filesystem | sed "s#%##g"`;

        for FS in "$Filesystem"; do
		echo "$FS" | awk -v THR_urg="$Def_urgent" -v  THR_cri="$Def_critical" -v THR_maj="$Def_major"  'BEGIN {
                                        format_header="%-50s %-10s %-12s %-15s %-8s %-8s\n"
                                        use_format="";
					metricType="Mb"
                                        printf(format_header, "MOUNT POINT", "TOTAL", "USED", "AVAILABLE", "IN USE", "FS");
                                }

                                {

                                        total=$2/1024;
                                        used=$3/1024;
                                        available=$4/1024;
                                        F_total=sprintf("%.0f", total);
                                        F_used=sprintf("%.0f", used);
                                        F_available=sprintf("%.0f", available);

                                        format="%-50s %-10s %-12s %-15s %-8s %-8s\n";
                                        urgent="\033[5;31;1m" format "\033[0m";
                                        critical="\033[31;1m" format "\033[0m";
                                        major="\033[33;1m" format "\033[0m";
                                        normal="\033[37;1m" format "\033[0m";
                                        low="\033[32;1m" format "\033[0m";

					if ($5 >= THR_maj && $5 < THR_cri) { use_format=major; }
					else if ( $5 >= THR_cri && $5 <= THR_urg) { use_format=critical;}
					else if ( $5 >= THR_urg ) {use_format=urgent;}
					else {use_format=normal;}
					printf(use_format, $1, F_total"("metricType")", F_used "("metricType")", F_available"("metricType")", $5"%", $6)
                                }'
        done
;;

 k | K )

        Filesystem=`df -Pk | grep -v ^Filesystem | sed "s#%##g"`; 

        for FS in "$Filesystem"; do

                echo "$FS" | awk -v THR_urg="$Def_urgent" -v  THR_cri="$Def_critical" -v THR_maj="$Def_major" 'BEGIN {
                                        format_header="%-50s %-10s %-12s %-15s %-8s %-8s\n"
                                        use_format="";
					metricType="Kb"
                                        printf(format_header, "MOUNT POINT", "TOTAL", "USED", "AVAILABLE", "IN USE", "FS");
                                }

                                {

					total=$2;
                                        used=$3;
                                        available=$4;
                                        F_total=sprintf("%.0f", total);
                                        F_used=sprintf("%.0f", used);
                                        F_available=sprintf("%.0f", available);

                                        format="%-50s %-15s %-12s %-18s %-8s %-8s\n";
                                        urgent="\033[5;31;1m" format "\033[0m";
                                        critical="\033[31;1m" format "\033[0m";
                                        major="\033[33;1m" format "\033[0m";
                                        normal="\033[37;1m" format "\033[0m";
                                        low="\033[32;1m" format "\033[0m";

                                        if ($5 >= THR_maj && $5 < THR_cri) { use_format=major; }
                                        else if ( $5 >= THR_cri && $5 <= THR_urg) { use_format=critical;}
                                        else if ( $5 >= THR_urg ) {use_format=urgent;}
                                        else {use_format=normal;}
					printf(use_format, $1, F_total"("metricType")", F_used "("metricType")", F_available"("metricType")", $5"%", $6)
                                }'
        done
 ;;
 
 d | D )

 wait=$OPTARG;
 
 if [ -f $prFile ]; then
	 oldPrFile=`cat $prFile`;
	 pkill $oldPrFile 2>/dev/null;
 fi
 

 log "" "" "" "" "START" $prPID "$wait";

 while true; do
  Filesystem=`df -Pk | grep -v ^Filesystem | sed "s#%##g"`;
	while read FS; do
		FS_name=`echo $FS | awk '{ print $1 }'`;
                used=`echo $FS | awk '{ print $3 }'`;
                available=`echo $FS | awk '{ print $4 }'`;
                percent=`echo $FS | awk '{ print $5 }'`;
		if [[ $percent -ge $Def_urgent ]]; then
			alert $SlackWebHook "Urgent" $FS_name $percent $available ":name_badge:";
		        log $FS_name $used $available $percent "URGENT"; 	
		elif [[ $percent -ge $Def_critical ]]; then
			alert $SlackWebHook "Critical" $FS_name $percent $available ":bomb:";
		        log $FS_name $used $available $percent "CRITICAL"; 	
		else	
		        log $FS_name $used $available $percent "INFO";
		fi	

        done <<< "$Filesystem"
 sleep $wait; 
 done &
 prPID=$!
 echo $prPID > $prFile;
 ;;

 s | S )
  log "" "" "" "" "STOP" "" "`whoami`";	
  pkill -F $prFile; 2>/dev/null
  rm -f $prFile;
  exit 0; 
 ;;
 h | H )
	usage
 ;;

 \? )
  usage
 ;;
 esac
done
